# Generated by Django 2.2 on 2020-11-26 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Files',
        ),
    ]
