# Generated by Django 2.2 on 2020-11-23 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Remark1', models.CharField(max_length=20)),
                ('Remark2', models.CharField(max_length=20)),
                ('File', models.FileField(upload_to='')),
            ],
            options={
                'db_table': 'ZipFileTest',
            },
        ),
    ]
